name: gdg_alicante_badges_backend
description: Backend server for the GDG Alicante Badges generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  csv: ^6.0.0
  github: ^9.25.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  image: ^4.5.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mustache_template: ^2.0.1
  http: ^1.5.0

dev_dependencies:
  coolint: ^2.0.1
